[tool.cibuildwheel]
# Skip building on CPython 3.6 on all platforms
skip = "cp36-*"

[tool.cibuildwheel.macos]
before-all = "brew install gcc"

[project]
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=42", "wheel", "scikit-build", "cmake>=3.18", "ninja", "numpy>=1.21"]
