

planet:
  surface-gravity: 980.7 # cm/s2
  fscale: 1.0
  surface-albedo: 0.25
  tropopause-altitude: 1.1e6 # cm
  planet-radius: 6.371e8 # cm
  surface-pressure: 1.013 # bar
  planet: EARTH

settings:
  diurnal-averaging-factor: 0.5
  lgrid: 0
  io2: 2
  ino: 0
  epsj: 1.0e-9
  prono: 1.0e9
  frak: 1
  hcdens: 0.63
  ihztype: 0
  solar-zenith-angle: 50.0
  lightning: true
  